### ISSUE TITLE
Phi calculation

### ISSUE THREAD

**Issue by doublex** [jabr/scuttleraft#1]
There are different implementations for Phi. Are these better?
E.g.:
https://github.com/samueleresca/phi-accrual-failure-detector/blob/main/phi-accrual-failure-detector/phi_accrual_failure_detector.py#L160

**Comment by jabr** [comment]
The failure detector here works fundamentally the same way as the phi accrual method, but I've simplified the math and made some approximations to streamline the implementation:
- the exp/log step isn't necessary if you're just using it for a boolean threshold check
- replaced the windowed mean/variance with a time decaying weighted estimate
 
I'm not opposed to having multiple implementations, however, and making the failure detector approach a configurable option.

**Comment by doublex** [comment]
Thank you for the explanation - and for all your efforts to implement this tricky paper!
